version: '3.8'  # Убедитесь, что у вас указан правильный формат версии

services:
  etl:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - elasticsearch
      - redis

  redis:
    container_name: redis
    image: redislabs/redismod:latest
    expose:
      - "6379"
    restart: always
    volumes:
      - redis_data:/data  # Исправлено имя тома

  elasticsearch:
    image: elasticsearch:8.7.0
    restart: always
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2048m -Xmx2048m
    ports:
      - ${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}
  
volumes:
  elasticsearch:
  redis_data:
